Add Dynatrace method to query SLO
google/slo-generator pull request #116
Opened 2021-01-27 13:49 UTC by clement-pruvot

Hello,

I added a new method query_sli to retrieve SLO already calculated in Dynatrace :

```
backend:
  class:                Dynatrace
  method:            query_sli
  api_url:              ${DYNATRACE_API_URL}
  api_token:         ${DYNATRACE_API_TOKEN}
  measurement:
    slo_id:             898a6875-a5f5-3066-9aa8-977a17b9432d
```

There is no breaking change.

2021-01-27 15:23 UTC, ocervell requested changes

2021-01-27 15:23 UTC, ocervell commented on slo_generator/backends/dynatrace.py
> +            LOGGER.debug(f'Response: {response}')
Let's always log the response, not only in the `else` cause - so that we can debug `put` / `post` methods also.

2021-01-27 15:23 UTC, ocervell commented on slo_generator/backends/dynatrace.py
> +        code = int(response.get('error', {}).get('code', 200))
can we avoid repeating `response.get('error', {})` by setting it as a variable before the `if` / `else` ?

2021-01-27 15:23 UTC, ocervell commented on slo_generator/backends/datadog.py
> +            return sli_value
This is Datadog-related, not Dynatrace, and is already in the latest master.
Try to merge the latest master into your branch instead.

2021-02-03 11:39 UTC, ocervell requested changes
Almost good, just need unit tests to pass, please add the appropriate fixture JSON and modify the Dynatrace mock function to add the "SLO get" endpoint.

2021-05-18 19:23 UTC, lvaylet commented
Hi @clement-pruvot, do you need assistance on this PR? Can I help? I would love to contribute to `slo-generator`. Fixing some unit tests sounds like a good first step. What do you think?

2021-09-28 11:34 UTC, merged