feat(Backend): Add Opensearch as a backend provider
google/slo-generator pull request #348
Opened 2023-09-01 09:02 UTC by maximepln

2023-09-06 08:56 UTC, maximepln commented
Hi @lvaylet, @bkamin29 

What are your thought on this ? 

I had to disable py-lint code duplication to have the CI to pass.

2023-09-06 12:34 UTC, lvaylet commented
Hi @maximepln, thanks a lot for this submission. I will take a look at it shortly. Regarding your choice of going with two different backends (with some duplicate code), I ended up doing the exact same thing to support MQL in Cloud Monitoring on top of the existing MQF backend.

2023-09-06 12:59 UTC, lvaylet requested changes
A few minor changes left. Thanks for the good work!

2023-09-06 12:59 UTC, lvaylet commented on docs/providers/opensearch.md
> +Using the `opensearch` backend class, you can query any metrics available in Opensearch to create an SLO.
OpenSearch with a capital S, as used on [their website](https://opensearch.org/)? A global search/replace is probably the best option here.

2023-09-06 12:59 UTC, lvaylet commented on slo_generator/backends/opensearch.py
> +class OpensearchBackend:
Again, OpenSearchBackend with a capital S?

2023-09-06 13:41 UTC, maximepln commented
@lvaylet Thanks for the feedback,

I did the modification in the code. 

I voluntarily let the backend name to `opensearch` in the yaml file as they are all in snake_case and I didn't want to add any complexity on that side.

Don't hesitate if you have any other comment.

2023-09-06 15:05 UTC, maximepln commented
Thanks for the feedback @lvaylet, 

I updated to code to use `OpenSearch` instead of `Opensearch`

Don't hesitate if you have any other comments

2023-09-08 12:33 UTC, lvaylet requested changes
Thanks a lot for going over every instance of OpenSearch in the commits. I suggested a couple more changes to remain consistent with other backends (Cloud Monitoring specifically).

2023-09-08 12:33 UTC, lvaylet commented on docs/providers/opensearch.md
> +Using the `OpenSearch` backend class, you can query any metrics available in OpenSearchBackend to create an SLO.
available in **OpenSearch**

2023-09-08 12:33 UTC, lvaylet commented on docs/providers/opensearch.md
> +The following method is available to compute SLOs with the `OpenSearch` backend:
`open_search` to remain consistent with the Cloud Monitoring documentation

2023-09-28 08:54 UTC, maximepln commented
Hi @lvaylet, 

Sorry for the delay to respond, I was away on holiday. 

Hope everything is fine now

2023-10-03 17:27 UTC, lvaylet commented
I will take a look tomorrow afternoon.

2023-10-04 09:37 UTC, lvaylet approved these changes

2023-10-04 09:37 UTC, merged