refactor(tests): allow to setup the Datadog host URL
google/slo-generator pull request #359
Opened 2023-10-16 15:28 UTC by sdenef-adeo

For local tests purposes, we may want to update the Datadog host URL used for Datadog API requests.

Example: testing rate limiting
Running a local NginX server acting as a Datadog API mock. We can set a dedicated rate-limit config without burning our Datadog instance (called "organization" by Datadog) quota.

Reminder: https://docs.datadoghq.com/api/latest/rate-limits/

2023-11-03 12:55 UTC, sdenef-adeo commented
Sorry, I made a typo, then I updated the PR.

It's `api_host` then the client will initialize accordingly.
cf https://datadogpy.readthedocs.io/en/latest/#datadog.initialize

Also part of [docs/provides/datadog.md
](https://github.com/google/slo-generator/blob/master/docs/providers/datadog.md#backend)

> Optional arguments to configure Datadog are documented in the Datadog initialize method [here](https://github.com/DataDog/datadogpy/blob/058114cc3d65483466684c96a5c23e36c3aa052e/datadog/__init__.py#L33). You can pass them in the backend section, such as specifying api_host: api.datadoghq.eu in order to use the EU site.

2023-11-22 13:31 UTC, lvaylet requested changes
Got it. Just a tiny change and we can merge.

2023-11-22 13:31 UTC, lvaylet commented on samples/config.yaml
> +    api_host: ${DATADOG_HOST}
Can we make that `DATADOG_API_HOST` to keep a consistent naming?

2023-11-22 13:31 UTC, lvaylet commented on tests/unit/test_stubs.py
> +    "DATADOG_HOST": "fake",
Same here: `DATADOG_API_HOST`

2023-11-27 16:51 UTC, lvaylet commented
Thanks @sdenef-adeo. Let me take care of the new vulnerabilities reported by `safety` and let's merge.

2023-11-29 13:38 UTC, lvaylet commented
The new vulnerability reported by `safety check` was handled in #397. I will move forward and merge this PR.

2023-11-29 13:39 UTC, merged