Fun/error budget ratio implementation
google/slo-generator pull request #413
Opened 2024-01-02 22:59 UTC by mrtergl

2024-01-05 21:31 UTC, lvaylet requested changes
Thanks a lot for this PR. I added a few comments.

2024-01-05 21:31 UTC, lvaylet commented on setup.cfg
> +    safety >=2.3.5
Is this necessary, as it does not seem to solve the issue of Python 3.11 tests not completing successfully?

2024-01-05 21:31 UTC, lvaylet commented on slo_generator/exporters/bigquery.py
> +        "name": "consumed_budget_ratio",
`error_budget_consumed_ratio` to remain consistent with the naming of similar variables?

2024-01-05 21:31 UTC, lvaylet commented on slo_generator/report.py
> +    consumed_budget_ratio: float
same here: `error_budget_consumed_ratio`?

2024-01-05 21:31 UTC, lvaylet commented on slo_generator/report.py
> +            consumed_budget_ratio=eb_ratio,
same here: `error_budget_consumed_ratio`?

2024-01-05 21:31 UTC, lvaylet commented on tests/unit/fixtures/slo_report_v2.json
> +  "consumed_budget_ratio": 19.9999999999999,
same here: `error_budget_consumed_ratio`?

2024-01-09 14:14 UTC, lvaylet commented
Thanks a lot @mrtergl. The code looks good. Let me just think about the consequences for current users of the BigQuery exporter. I think everything will be fine, as BigQuery allows adding more columns, but I want to run some tests first. Also, I do not want this new column to induce extra cost for users who rely a lot on the SLO Generator, with millions of calls every month.

2024-01-09 15:37 UTC, mrtergl commented
I appreciate for your time and valuable review. @lvaylet

2024-01-12 14:31 UTC, lvaylet approved these changes

2024-01-12 14:32 UTC, lvaylet commented
I will move forward with merging this to the `main` branch. Then I will use the Cloud Run Service deployed by the CI/CD pipeline to run a few tests.

2024-01-12 14:33 UTC, merged